[phases.setup]
nixPkgs = ["python313", "libGL", "glib", "libxcb"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
